Updated to rxdart: ^0.26.0 & added null-saftey
MaikuB/incrementally_loading_listview pull request #21
Opened 2021-06-11 04:54 UTC by tkeithblack

This pull request includes two changes. One is to update to rxdart: ^0.26.0, the other is addition of null-saftey.

2021-06-13 04:31 UTC, MaikuB commented on pubspec.yaml
> +  sdk: ">=2.13.0 <3.0.0"
Could these constraints be lowered to earliest version with null safety support?

2021-06-13 04:32 UTC, MaikuB requested changes
Thanks a lot for the PR. Besides the comment I left on the constraints. Would you able to help look at migrating the example app itself to use null safety?

2021-06-20 00:30 UTC, merged

2021-06-20 00:30 UTC, MaikuB commented
Made the changes myself so all good, thanks :)

2021-06-20 20:30 UTC, tkeithblack commented
Thanks for doing the merge. Sorry I didn't get back to you on migrating the example.